# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Java CI

on: [push]

jobs:
  build:
    name: Build And Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Upload build reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Download jar artifact
        uses: actions/download-artifact@v3
        with:
          name: Package

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release jar artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.jar
          prerelease: true
          draft: true
